# Generated by Django 5.0.4 on 2024-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_website_settings_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='domain_name',
            field=models.JSONField(default=[]),
        ),
    ]
