# Generated by Django 5.0.4 on 2024-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_settings_domain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='settings',
            name='domain_name',
            field=models.ManyToManyField(to='app.domain'),
        ),
    ]
