# Generated by Django 5.0.4 on 2024-04-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_domain_remove_settings_domain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='component_name',
            field=models.CharField(choices=[('HOME', 'HOME'), ('AOUT US', 'AOUT US'), ('IMAGE GALLERY', 'IMAGE GALLERY'), ('AMENITIES', 'AMENITIES'), ('PROJECTS', 'PROJECTS'), ('CONFIG', 'CONFIG'), ('CONTACT US', 'CONTACT US')], max_length=200),
        ),
    ]
