# Generated by Django 5.0.4 on 2024-04-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_sections_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='component_name',
            field=models.CharField(choices=[(None, None), ('HOME', 'HOME'), ('ABOUT US', 'ABOUT US'), ('IMAGE GALLERY', 'IMAGE GALLERY'), ('AMENITIES', 'AMENITIES'), ('PROJECTS', 'PROJECTS'), ('CONFIG', 'CONFIG'), ('CONTACT US', 'CONTACT US')], default=None, max_length=200),
        ),
    ]
