# Generated by Django 5.0.4 on 2024-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_sections_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_type',
            field=models.CharField(choices=[('gallery', 'gallery'), ('amenities', 'amenities'), ('master plan', 'master plan'), ('floor plan', 'floor plan'), ('Cover Image', 'Cover Image'), ('Home', 'Home'), ('About us', 'About us')], default='gallery', max_length=200),
        ),
    ]
