# Generated by Django 5.0.4 on 2024-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_images_img_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='config',
            field=models.CharField(choices=[('1 RK', '1 RK'), ('1 BHK', '1 BHK'), ('1.5 BHK', '1.5 BHK'), ('2 BHK', '2 BHK'), ('2.5 BHK', '2.5 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK')], max_length=200),
        ),
    ]
