# Generated by Django 5.0.4 on 2024-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_configuration_measurements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_type',
            field=models.CharField(choices=[('gallery', 'gallery'), ('amenities', 'amenities'), ('master plan', 'master plan'), ('floor plan', 'floor plan'), ('Cover Image', 'Cover Image'), ('Home', 'Home'), ('About us', 'About us'), ('location', 'location')], default='gallery', max_length=200),
        ),
    ]
